### ISSUE TITLE
Example?

### ISSUE THREAD

**Issue by egberts** [JohnJocoo/AhoCorasick#1]
I think it would be cool to have a 3 or 4 line example to help master this template.

So far, I've mastered the following:

`
int
main()
{
    AhoCorasick<std::string> ac;

    ac.addPattern(std::string("dog");
    ac.addPattern(std::string("cat");

    auto str = ac.matcher();
}` 

But I cannot come up with a working std::string comparator function and logic yet.

**Comment by JohnJocoo** [comment]
Hi Egberts!

This code actually was written as part of an interview test, so it lacks examples and documentation. Sorry for inconvenience. I've created simple example of how AhoCorasick class can be used:

```
  std::string string{"quick red fox jumps over lazy brown dog that owns brown house"};
  AhoCorasick<std::string> automation;
  automation.addPattern("quick");
  automation.addPattern("ck");
  automation.addPattern("azy");
  automation.addPattern("own");
  automation.addPattern("brown");
  
  auto matcher = automation.matcher();
  auto begin = std::begin(string);
  matcher.match([&begin](const std::string& pattern, decltype(begin) iterator)
  {
    std::cout << "Matched \"" << pattern << "\" on position "
      << std::distance(begin, iterator) << std::endl;
      return false;
  }, std::begin(string), std::end(string));
```
Outputs is:
```
Matched "quick" on position 0
Matched "ck" on position 3
Matched "azy" on position 26
Matched "brown" on position 30
Matched "own" on position 32
Matched "own" on position 45
Matched "brown" on position 50
Matched "own" on position 52
```
So first you create instance of AhoCorasick template class where template parameter is type of patterns that will be used. Then you add patterns to search for and get matcher object (automation.matcher()) that is able to perform actual search. Now you should call matcher.match() to search for patterns in data. Function match() receives callback function and iterators to data's begin and end, match() will search for patterns using Aho & Corasick state machine and call your callback on every pattern matched. Callback itself must receive 2 arguments:

1. Pattern that triggered match
2. Iterator to place in data where match happened (start of matched data).

Also callback's return type should be bool (or something convertible to bool). It must return false to continue search or true to stop and quit from match() function.

As some more advanced note - data is not required to be the same type as pattern. It just must be iterable and its values should be comparable with pattern values.
```
  std::vector<int> not_a_string;
  std::copy(std::begin(string), std::end(string), std::back_inserter(not_a_string));
  auto begin2 = std::begin(not_a_string);
  matcher.match([&begin2](const std::string& pattern, decltype(begin2) iterator)
  {
    std::cout << "Matched \"" << pattern << "\" on position "
      << std::distance(begin2, iterator) << std::endl;
      return false;
  }, std::begin(not_a_string), std::end(not_a_string));
```
If information provided would be enough, I will add it as an example and Readme to project and close issue.
